# Generated by Django 4.2.8 on 2024-01-01 20:58

import clinicaApp.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0003_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=django_enumfield.db.fields.EnumField(enum=clinicaApp.models.Specialite),
        ),
    ]
