# Generated by Django 4.2.8 on 2024-01-03 16:40

import clinicaApp.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0004_alter_medecin_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='DateNaissance',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.EmailField(default='name@domain.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medecin',
            name='num_tel',
            field=models.IntegerField(default=511111111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medecin',
            name='sexe',
            field=django_enumfield.db.fields.EnumField(enum=clinicaApp.models.sexe),
        ),
    ]
