# Generated by Django 4.2.8 on 2024-01-04 02:34

import clinicaApp.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0007_rendez_vous_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='service',
            field=django_enumfield.db.fields.EnumField(enum=clinicaApp.models.Specialite),
        ),
    ]
