# Generated by Django 4.2.8 on 2024-01-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0009_rendez_vous_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('ID_Medicament', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('Dosage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('ID_Operation', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Salle_Operation',
            fields=[
                ('ID_Salle', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_de_salle', models.IntegerField(default=0)),
                ('Disponibilite', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='suivipostoperatoire',
            name='Medecin',
        ),
        migrations.RemoveField(
            model_name='suivipostoperatoire',
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='Rendez_Vous',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='Consultation',
        ),
        migrations.AddField(
            model_name='consultation',
            name='estPasser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.salle_consultation'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Antecedents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Consultations',
            field=models.ManyToManyField(blank=True, to='clinicaApp.consultation'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='DateCreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.consultation'),
        ),
        migrations.DeleteModel(
            name='Calendrier',
        ),
        migrations.DeleteModel(
            name='SuiviPostOperatoire',
        ),
        migrations.AddField(
            model_name='operation',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.salle_operation'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Medicaments',
            field=models.ManyToManyField(blank=True, to='clinicaApp.medicament'),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.operation'),
        ),
    ]
