# Generated by Django 4.2.8 on 2024-01-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0010_medicament_operation_salle_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='Operations',
            field=models.ManyToManyField(blank=True, to='clinicaApp.operation'),
        ),
    ]
