# Generated by Django 4.2.8 on 2024-01-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0011_dossiermedical_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='Medecin',
        ),
        migrations.AddField(
            model_name='operation',
            name='estPasser',
            field=models.BooleanField(default=False),
        ),
    ]
