# Generated by Django 4.2.8 on 2024-01-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0012_remove_operation_date_remove_operation_medecin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='Consultations',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='Operations',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Consultations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.consultation'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Operations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.operation'),
        ),
    ]
