# Generated by Django 4.2.8 on 2024-01-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0013_remove_dossiermedical_consultations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='Consultations',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='Operations',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Consultations',
            field=models.ManyToManyField(blank=True, to='clinicaApp.consultation'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='Operations',
            field=models.ManyToManyField(blank=True, to='clinicaApp.operation'),
        ),
    ]
