# Generated by Django 4.2.8 on 2024-01-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0016_remove_dossiermedical_operations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='Patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.patient'),
        ),
    ]
