# Generated by Django 5.0 on 2023-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('ID_Consultation', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnostic', models.CharField(max_length=50)),
                ('Traitement', models.CharField(max_length=50)),
                ('commentaire', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('ID_Medecin', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ID_Patient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salle_Consultation',
            fields=[
                ('ID_Salle', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('ID_Dossier', models.AutoField(primary_key=True, serialize=False)),
                ('Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.consultation')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_Vous',
            fields=[
                ('ID_RDV', models.AutoField(primary_key=True, serialize=False)),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medecin')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='Rendez_Vous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.rendez_vous'),
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('ID_Calendrier', models.AutoField(primary_key=True, serialize=False)),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medecin')),
                ('Salle_Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.salle_consultation')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviPostOperatoire',
            fields=[
                ('ID_Suivi', models.AutoField(primary_key=True, serialize=False)),
                ('Evolution', models.CharField(max_length=50)),
                ('Recommandation', models.CharField(max_length=50)),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medecin')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.patient')),
            ],
        ),
    ]
