# Generated by Django 5.0 on 2023-12-23 18:38

import clinicaApp.models
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DateNaissance',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='ramybouchareb@outlook.com', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='num_tel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=django_enumfield.db.fields.EnumField(enum=clinicaApp.models.sexe),
        ),
    ]
