# Generated by Django 5.0 on 2023-12-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0002_patient_datenaissance_patient_email_patient_num_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='test@domain.com', max_length=254),
        ),
    ]
